-- Create the patients table
CREATE TABLE patients (
   ID INT GENERATED ALWAYS AS IDENTITY,
   NAME VARCHAR (20),
   DATE_OF_BIRTH DATE,
   PRIMARY KEY (ID)
);


-- Create the medical-histories table
CREATE TABLE medical_histories (
   ID INT GENERATED ALWAYS AS IDENTITY,
   ADMITTED_AT TIMESTAMP,
   PATIENT_ID INT,
   CONSTRAINT FK_PATIENTS FOREIGN KEY(PATIENT_ID) REFERENCES patients(ID),
   STATUS VARCHAR(20),
   PRIMARY KEY(ID)
);